document.addEventListener("DOMContentLoaded", function() {
    const bibtexData =`
	
        @article{hofmeyer2006,
            title={Interaction of Spatial and Structural Design, an Automated Approach},
            author={Hofmeyer, Herm and Rutten, Harry and Fijneman, Henk},
            journal={Design Studies},
            volume={27},
            number={4},
            pages={423--438},
            year={2006},
            publisher={Elsevier},
            abstract={This paper presents two procedures that are able to allow interaction between spatial design and structural design. ‘Zone generation’ and ‘room positioning within structural constraints’ both facilitate uni-directional interaction. Using these procedures consecutively yields an improved design method that provides interaction between spatial and structural design. A computer program in Prolog-2 has been developed for demonstration purposes. The method developed here can be applied flexibly because it is limited to only two procedures and there is the added advantage that the procedures can easily be extended or redefined.},     note={ISI Journal Article},
            link={https://www.sciencedirect.com/science/article/abs/pii/S0142694X05000505}
        }
		
		@article{hofmeyer2006,
            title={Interaction of Spatial and Structural Design, an Automated Approach},
            author={Hofmeyer, Herm and Rutten, Harry and Fijneman, Henk},
            journal={Design Studies},
            volume={27},
            number={4},
            pages={423--438},
            year={2006},
            publisher={Elsevier},
            abstract={This paper presents two procedures that are able to allow interaction between spatial design and structural design. ‘Zone generation’ and ‘room positioning within structural constraints’ both facilitate uni-directional interaction. Using these procedures consecutively yields an improved design method that provides interaction between spatial and structural design. A computer program in Prolog-2 has been developed for demonstration purposes. The method developed here can be applied flexibly because it is limited to only two procedures and there is the added advantage that the procedures can easily be extended or redefined.},      note={ISI Journal Article},
            link={https://www.sciencedirect.com/science/article/abs/pii/S0142694X05000505}
        }
		
		@article{hofmeyer2007,
            title={Cyclic Application of Transformations using Scales for Spatially or Structurally Determined Design},
            author={Hofmeyer, Herm},
            journal={Automation in Construction},
            volume={16},
            number={5},
            pages={664--673},
            year={2007},
            publisher={Elsevier},
            abstract={In multi-disciplinary design processes in the field of Architecture, Engineering, and Construction (AEC), the design of buildings is continuously subject to transformations by the individual disciplines, e.g. when the structural designer makes a structural design for the building using the spatial design of the architect as a starting point. This paper will show that by introducing a scale for evaluating the design stages between the individual disciplines in a cyclic application of transformations, new insights can be obtained into the relationship between spatial and structural design in addition to the overall multi-disciplinary design process. The proposed design stage scale will indicate whether a design is developed to create space (spatially determined) or to create structure (structurally determined). Examples are presented for small-scale buildings and specific transitions. They will show that fundamentals, e.g. diaphragms separate spaces, will automatically be generated by the proposed cyclic application of transformations. The method also allows conclusions to be drawn from the design process, e.g. the spatial design layout will determine whether the ensuing design steps will evolve towards a spatially determined design or towards an integrated design. The idea of cyclic application with evaluation scales can be developed further by applying it to large scale buildings with additional and/or other types of transitions and scales.},
			note={ISI Journal Article},
            link={https://www.sciencedirect.com/science/article/abs/pii/S0926580506001233}
        }
		
		@article{hofmeyer2008,
            title={Spatial to Kinematically Determined Structural Transformations},
            author={Hofmeyer, Herm and Bakker, Monique},
            journal={Advanced Engineering Informatics},
            volume={22},
            number={3},
            pages={393--409},
            year={2008},
            publisher={Elsevier},
            abstract={To understand the building design process and to help designers involved, the idea of a research engine has been developed: In this engine cyclic transformations take place between spatial and structural building designs. With this engine, a design process can be studied closely and subjected to improvement, and designers can be supported. To develop the engine, in this paper a part of it is studied, namely the transformation from spatial to structural design, which can be divided into four sub transformations: (1) from spatial design to structural topology; (2) from structural topology to mechanical model; (3) from mechanical model to finite element model; (4) from finite element model to design recommendations. For the first sub transformation, two different techniques are presented: Spatial–Structural Transformation Rules and Element Selection. For the second sub transformation, also two techniques are presented: Element Approach and System Approach. Where possible, data models in EXPRESS and process models in IDEF0 are used. For the third and fourth sub transformation, new procedures have been developed using data models in EXPRESS. To test the data and process models for all four sub transformations, a simplified two-storey building, derived from a real six-storey apartment building, is used as case study. It can be concluded that the developed sub transformations function well, related to their application in the research engine, and that their development raises new research questions that have to be solved in the near future.},
            note={ISI Journal Article},
            link={https://www.sciencedirect.com/science/article/abs/pii/S147403460800030X}
        }
		
		@article{hofmeyer2011,
            title={Pre-Processing Parallel and Orthogonal Geometrical Design Components to Be Used within the Finite Element Method},
            author={Hofmeyer, Herm and Van Roosmalen, Maartje and Gelbal, Firat},
            journal={Advanced Engineering Informatics},
            volume={25},
            number={2},
            pages={245--258},
            year={2011},
            publisher={Elsevier},
            abstract={Two methods for pre-processing of (parallel and orthogonal positioned) structural design elements, to be used for specifying kinematically undetermined behaviour within the finite element method, are presented. One method is based on first checking line–line combinations, using a (2D) projection technique, followed by investigating line–area combinations employing a line–line combination related technique. These procedures (line–line and line–area) are repeated until convergence occurs. The method is finalised by pattern recognition to find all new areas within the original areas. The second method is also based on (iteratively) checking line–line combinations and line–area combinations but now line–line combinations are studied using a line–area intersection technique and line–area combinations are investigated with a technique that makes (expensive) pattern recognition superfluous. Both methods are implemented in C++ and are compared for correctness and efficiency by using academic and building design examples. It can be concluded that the second method seems an appropriate candidate for further implementation.},
            note={ISI Journal Article},
            link={https://www.sciencedirect.com/science/article/abs/pii/S1474034610000480}
        }
		
		@article{smulders2012,
            title={An Automated Stabilisation Method for Spatial to Structural Design Transformations},
            author={Smulders, Carola and Hofmeyer, Herm},
            journal={Advanced Engineering Informatics},
            volume={26},
            number={4},
            pages={653--950},
            year={2012},
            publisher={Elsevier},
            abstract={A spatial–structural design process can be investigated via a so-called research engine, in which a spatial design is transformed into a structural design and vice versa. During the transformation from a spatial into a structural design, it is necessary to obtain a stable structural model, so that a structural analysis can be carried out. This article presents four methods to automate the (normally carried out intuitively) stabilisation process, using data related to a structural design’s geometry and its instability modes. The methods all use the null space and associated null vectors of the structural stiffness matrix. Then each null vector is resolved by either (a) rod addition, (b) plane addition, (c) hinge fixation by single rod substitution, or (d) hinge fixation by coupled rod substitution. The methods have been implemented in C++ and several test cases have been carried out. The test cases explain why (a) rod addition provides the most realistic solutions, (b) if several methods are used subsequently for one problem, superfluous elements are inevitable, (c) there is a serious influence on the performance for various systems of key point numbering, (d) the efficiency of the methods is not optimal and may be improved by some suggested strategies.},
            note={ISI Journal Article},
            link={https://www.sciencedirect.com/science/article/abs/pii/S1474034612000213}
        }	
		
		@article{davila2013,
            title={Automated Generation of Structural Solutions based on Spatial Designs},
            author={Davila Delgado, Juan and Hofmeyer, Herm},
            journal={Automation in Construction},
            volume={35},
            pages={528--541},
            year={2013},
            publisher={Elsevier},
            abstract={To aid in the understanding of design processes and to support the involved actors, a "Research Engine" (RE) is under development. The RE is a set of automated computational processes that simulate a spatial–structural design process. The first developed phase of the RE in which a Spatial Design is transformed into a Structural Solution is presented. It generates a structure, performs a structural analysis and provides an indication of its structural behavior. A case-study presents three building spatial designs which are used to generate 36 different structural solutions. A study of the influence of the transformations in the results is presented. For instance, structural zoning has a larger influence on the maximum displacements of the structural solutions than the amount of structural mass. Additionally, in design processes' early stages, this phase of the RE could help designers to devise different structural solutions and to quickly predict their structural behavior.},
            note={ISI Journal Article},
            link={https://www.sciencedirect.com/science/article/abs/pii/S0926580513001052}
        }	
		
		@article{hofmeyer2013,
            title={Automated Design Studies: Topology versus One-Step Evolutionary Structural Optimisation},
            author={Hofmeyer, Herm and Davila Delgado, Juan},
            journal={Advanced Engineering Informatics},
            volume={27},
            pages={427--443},
            year={2013},
            publisher={Elsevier},
            abstract={This paper presents the development of a virtual toolbox for the study of spatial–structural design processes. It will be able to transform a spatial design into a structural design. After structural optimisation, the structural design is interpreted as a spatial design. This spatial design is then modified to comply with the initial design requirements after which a new cycle starts. The transformation and optimisation processes within the toolbox can be altered, allowing automated design studies to be carried out. In this article, two processes for the structural optimisation are investigated to determine which is most suitable for specific conditions. These two processes are: (a) Topology Optimisation applied to complete structural systems for buildings; (b) Evolutionary Structural Optimisation for which only the first step is used. It can be concluded that: (a) although Topology Optimisation is formally more correct, One-Step Evolutionary Structural Optimisation will yield almost the same qualitative results, (b) quantitatively the methods cannot be compared exactly, however, it is likely that Topology Optimisation results in more efficient structures and (c) Topology Optimisation always leads to stable structures, whereas One-Step Evolutionary Structural Optimisation may yield a singular stiffness matrix, although this has no influence on the spatial design derived from the optimised structural design. It is intended to utilise the optimisation techniques in the virtual toolbox leading to design studies and to transcend additional transformation and optimisation processes in the virtual tool box via formal description. Fields of application are the academic study of spatial–structural design processes (i.e. design theory), the optimisation of all possible structural design types (i.e. design optimisation), and the generation of design instances (i.e. generative design).},
            note={ISI Journal Article},
            link={https://www.sciencedirect.com/science/article/pii/S1474034613000256}
			}

		@article{hofmeyer2015,
            title={Coevolutionary and Genetic Algorithm Based Building Spatial and Structural Design},
            author={Hofmeyer, Herm and Davila Delgado, Juan},
            journal={AIEDAM-Artificial Intelligence for Engineering Informatics},
            volume={29},
            pages={351--370},
            year={2015},
            publisher={Cambridge University Press},
            abstract={This paper presents the development of a virtual toolbox for the study of spatial–structural design processes. It will be able to transform a spatial design into a structural design. After structural optimisation, the structural design is interpreted as a spatial design. This spatial design is then modified to comply with the initial design requirements after which a new cycle starts. The transformation and optimisation processes within the toolbox can be altered, allowing automated design studies to be carried out. In this article, two processes for the structural optimisation are investigated to determine which is most suitable for specific conditions. These two processes are: (a) Topology Optimisation applied to complete structural systems for buildings; (b) Evolutionary Structural Optimisation for which only the first step is used. It can be concluded that: (a) although Topology Optimisation is formally more correct, One-Step Evolutionary Structural Optimisation will yield almost the same qualitative results, (b) quantitatively the methods cannot be compared exactly, however, it is likely that Topology Optimisation results in more efficient structures and (c) Topology Optimisation always leads to stable structures, whereas One-Step Evolutionary Structural Optimisation may yield a singular stiffness matrix, although this has no influence on the spatial design derived from the optimised structural design. It is intended to utilise the optimisation techniques in the virtual toolbox leading to design studies and to transcend additional transformation and optimisation processes in the virtual tool box via formal description. Fields of application are the academic study of spatial–structural design processes (i.e. design theory), the optimisation of all possible structural design types (i.e. design optimisation), and the generation of design instances (i.e. generative design).},
            note={ISI Journal Article},
			link={https://www.cambridge.org/core/journals/ai-edam/article/coevolutionary-and-genetic-algorithm-based-building-spatial-and-structural-design/0F8DBF544442D699C5A073B1E6695F2C}
        }				
		
		@article{hofmeyer2017,
            title={The Generation of Hierarchic Structures via Robust 3D Topology Optimisation},
            author={Hofmeyer, Herm and Schevenels, Mattias and Boonstra, Sjonnie},
            journal={Advanced Engineering Informatics},
            volume={33},
            pages={440--455},
            year={2017},
            publisher={Elsevier},
            abstract={Commonly used building structures often show a hierarchic layout of structural elements. It can be questioned whether such a layout originates from practical considerations, e.g. related to its construction, or that it is (relatively) optimal from a structural point of view. This paper investigates this question by using topology optimisation in an attempt to generate hierarchical structures. As an arbitrarily standard design case, the principle of a traditional timber floor that spans in one direction is used. The optimisation problem is first solved using classical sensitivity and density filtering. This leads indeed to solutions with a hierarchic layout, but they are practically unusable as the floor boarding is absent. A Heaviside projection is therefore considered next, but this does not solve the problem. Finally, a robust approach is followed, and this does result in a design similar to floor boarding supported by timber joists. The robust approach is then followed to study a floor with an opening, two floors that span in two directions, and an eight-level concrete building. It can be concluded that a hierarchic layout of structural elements likely originates from being optimal from a structural point of view. Also clear is that this conclusion cannot be obtained by means of standard topology optimisation based on sensitivity or density filtering (as often found in commercial finite element codes); robust 3D optimisation is required to obtain a usable, constructible (or in the future: 3D printable) structural design, with a crisp black-and-white density distribution.},
            note={ISI Journal Article},
			link={https://www.sciencedirect.com/science/article/pii/S1474034617300617}
        }	
		
		@article{boonstra2018,
            title={Toolbox for Super-Structured and Super-Structure Free Multi-Disciplinary Building Spatial Design Optimisation},
            author={Boonstra, Sjonnie and Van der Blom, Koen and Hofmeyer, Herm and Emmerich, Michael and Van Schijndel, Jos and De Wilde, Pieter},
            journal={Advanced Engineering Informatics},
            volume={36},
            pages={86--100},
            year={2018},
            publisher={Elsevier},
            abstract={Multi-disciplinary optimisation of building spatial designs is characterised by large solution spaces. Here two approaches are introduced, one being super-structured and the other super-structure free. Both are different in nature and perform differently for large solution spaces and each requires its own representation of a building spatial design, which are also presented here. A method to combine the two approaches is proposed, because the two are prospected to supplement each other. Accordingly a toolbox is presented, which can evaluate the structural and thermal performances of a building spatial design to provide a user with the means to define optimisation procedures. A demonstration of the toolbox is given where the toolbox has been used for an elementary implementation of a simulation of co-evolutionary design processes. The optimisation approaches and the toolbox that are presented in this paper will be used in future efforts for research into- and development of optimisation methods for multi-disciplinary building spatial design optimisation.},
            note={ISI Journal Article},
			link={https://www.sciencedirect.com/science/article/pii/S1474034616303974}
        }	
		
		@article{boonstra2020,
            title={Conceptual Structural System Layouts via Design Response Grammars and Evolutionary Algorithms},
            author={Boonstra, Sjonnie and Van der Blom, Koen and Hofmeyer, Herm and Emmerich, Michael},
            journal={Automation in Construction},
            volume={116},
            pages={103900},
            year={2020},
            publisher={Elsevier},
            abstract={Two new methods to generate structural system layouts for conceptual building spatial designs are presented. The first method, the design response grammar, uses design rules—configurable by parameters—to develop a structural system layout step by step as a function of a building spatial design's geometry and preliminary assessments of the structural system under development. The second method, design via optimizer assignment, uses an evolutionary algorithm to assign structural components to a building spatial design's geometry. In this work, the methods are demonstrated for two objectives: minimal strain energy (a commonly used objective for structural topology optimization) and minimal structural volume. In a first case study three building spatial designs have been subjected to the methods: Design via optimizer assignment yields a uniformly distributed Pareto front approximation, which incorporates the best performing layouts among both methods. On the other hand, results of the design response grammar show that layouts that correspond to specific positions on the Pareto front (e.g. layouts that perform well for strain energy), share the same parameter configurations among the three different building spatial designs. By generalizing, specific points on the Pareto front approximation have been expressed in terms of parameter configurations. A second case study addresses the use of a generic material and generic dimensions in the assessment of structural system layouts. The study applies a technique similar to topology optimization to optimize the material density distribution of each individual structural component, which can be regarded as a part of determining materials and dimensions in more advanced stages of the design of a system layout. This optimization approach is applied to the layouts that are part of the Pareto front approximations as found by the evolutionary algorithm in the first case study, the study shows that—after optimization—the fronts remain the same qualitatively, suggesting that the methods produce results that are also useful in more advanced design stages. A final case study tests the generalization that is established in the first case study by using the found configurations for the design response grammar, and it is shown that the generated layouts indeed are positioned near the desired positions on the Pareto front approximation found by the evolutionary algorithm. Although the evolutionary algorithm can find better performing solutions among a better distributed Pareto front approximation, the design response grammar uses only a fraction of the computational cost. As such it is concluded that the design response grammar is a promising support tool for the exploration and structural assessment of conceptual building spatial designs. Future research should focus on more types of structural elements; more objectives; new constraints to ensure feasible solutions, especially stress constraints; and the application of state-of-the-art techniques like machine learning to find more generalizations.},
            note={ISI Journal Article},
			link={https://www.sciencedirect.com/science/article/pii/S0926580519301311}
        }	
		@article{claessens2020,
            title={Spatial Zoning for Better Structural Topology Design and Performance},
            author={Claessens, Dennis and Boonstra, Sjonnie and Hofmeyer, Herm},
            journal={Advanced Engineering Informatics},
            volume={46},
            pages={101162},
            year={2020},
            publisher={Elsevier},
            abstract={A new three-dimensional spatial zoning procedure that has been tailored to structural design is presented in this work. Zoning is the grouping of spaces or sub-parts of spaces such that the resulting spatial layout is logical from a disciplinary perspective. Two automated structural design methods, so-called grammars, have been defined to generate structural designs for zoned building spatial designs. The first grammar, here termed stable design grammar, places structural slabs at the boundaries of a zone, and columns at places where a zone intersects with a space. The second grammar, here termed unstable grammar, generates a structural frame that is unstable by definition. Via a new stabilization method, which is also presented in this work, the unstable structural frame is stabilized by considering the boundaries of a zone for the placement of stabilizing measures. In a case study, the zoning procedure is applied in conjunction with each of the design grammars to three distinct building spatial designs. The case study shows—for both design grammars—that structural designs use less material and are stiffer when they are generated based on a zoned building spatial design. Moreover, the zoning procedure has been tailored such that it yields a subset of all possible zoned designs for which, in general, the generated structural designs perform well.},
            note={ISI Journal Article},
			link={https://www.sciencedirect.com/science/article/pii/S1474034620301336}
        }	
		@article{boonstra2021,
            title={Hybridization of an Evolutionary Algorithm and Simulations of Co-Evolutionary Design Processes for Early-Stage Building Spatial Design Optimization},
            author={Boonstra, Sjonnie and Van der Blom, Koen and Hofmeyer, Herm and Emmerich, Michael},
            journal={Automation in Construction},
            volume={124},
            pages={103522},
            year={2021},
            publisher={Elsevier},
            abstract={Three methods for early-stage building spatial design optimization are presented, demonstrated, and compared for their qualities and limitations. The first, an evolutionary algorithm, can find well-distributed approximations of the Pareto front, but it uses many design evaluations and it can only explore a limited part of the entire design search space (i.e. the collection of all possible design solutions). The second, simulations of co-evolutionary design processes, can find improved design solutions relatively fast within an unrestricted design search space, however, they typically only find discretely distributed Pareto front approximations. For the third method, hybridization is proposed to combine the first two methods into two new hybrid methods, such that their advantages are combined and their disadvantages are diminished. The methods have been applied in an initial case study, which shows that hybridization can improve search efficiency and speed, and it can search larger design search spaces.},
            note={ISI Journal Article},
			link={https://www.sciencedirect.com/science/article/pii/S092658052031102X}
        }	
		
        @phdthesis{phdjuan,
            author={Davila Delgado, Juan},
            title={Building Structural Design Generation and Optimisation including Spatial Modification},
            school={Eindhoven University of Technology},
            year={2014},
            abstract={Four strategies have been developed that enable building structural design generation and optimisation, including spatial modification, at early stages of the building design process, and using a systematic and automated approach. All strategies have been implemented, applied to academic building spatial designs, and compared. They demonstrate that entire structural designs (instead of individual elements) can be optimised, design variants can be provided via real design process and evolutionary based rational and automated strategies, and spatial modification –by space deletion, scaling, and subdivision, or by random variation– increases the generation and optimisation possibilities for the structural design.},
            note={PhD Thesis},
            key={phdjuan},
			link={https://research.tue.nl/en/publications/building-structural-design-generation-and-optimisation-including-},
        }

		@phdthesis{phdkoen,
            author={Van der Blom, Koen},
            title={Multi-Objective Mixed-Integer Evolutionary Algorithms for Building Spatial Design},
			school={Leiden University},
            year={2019},
            abstract={Multi-objective evolutionary computation aims to find high quality (Pareto optimal) solutions that represent the trade-off between multiple objectives. Within this field there are a number of key challenges. Among others, this includes constraint handling and the exploration of mixed-integer search spaces. This thesis investigates how these challenges can be handled at the same time, and in particular how they can be applied in the multi-objective optimisation algorithms. These algorithms are developed in the context of the optimisation of building spatial designs, which describe the exterior shape of a building, and the internal division into different spaces. Spatial designs are developed early in the design process, and thus have a large impact on the final building design, and in turn also on the quality of the building. Here the structural and thermal performance of a building are optimised to reduce resource consumption. The main contributions of this thesis are as follows. Firstly, a representation for building spatial designs in is introduced. Secondly, specialised search operators are designed to ensure only feasible solutions will be explored. Thirdly, data about the discovered solutions is analysed to explain the results to domain experts. Finally, a general purpose multi-objective mixed-integer evolutionary algorithm is developed.},
            note={PhD Thesis},
            key={phdkoen},
			link={https://scholarlypublications.universiteitleiden.nl/handle/1887/81789},
        }

@phdthesis{phdsjonnie,
            author={Boonstra, Sjonnie},
            title={Multi-Disciplinary Optimization of Building Spatial Designs},
			school={Eindhoven University of Technology},
            year={2020},
            abstract={In this thesis, the optimization of preliminary building spatial designs is investigated for objectives relevant to structural design (maximum structural stiffness) and building physics (minimum cooling/heating demands). The evaluation of the multi-disciplinary objectives is achieved per discipline using a design grammar that generates a discipline model based on a building spatial design. Two different optimization methods are proposed, each using a tailored representation for building spatial designs. The first optimisation method uses principles observed in design practice to simulate design processes, and it can search a large dynamic range of possible designs, however, it has a low chance to find the best design within the considered ranges. The second method uses state-of-the-art evolutionary algorithms, which search a limited and static range of possible desings with a high chance to find the best design within that range. Accordingly, the two methods are combined into a new hybrid method, which is shown to enable the search of a large dynamic range of building spatial designs with a high chance to find the best design within the considered ranges. Finally, the possible applications of the developed methods in design practice have been studied, which are: learning new design rules from optimization data, using the design grammars for design support, incorporating the methods into the workflow of a design process, and including objectives from new disciplines.},
            note={PhD Thesis},
            key={phdsjonnie},
			link={https://research.tue.nl/en/publications/multi-disciplinary-optimization-of-building-spatial-designs},
        }
        @mastersthesis{mscherm,
            author={Hofmeyer, Herm},
            title={Konstruktief Ontwerpen met Behulp van Computerprogrammatuur},
            school={Eindhoven University of Technology},
            year={1994},
            abstract={This thesis presents two procedures that are able to allow interaction between spatial design and structural design. ‘Zone generation’ and ‘room positioning within structural constraints’ both facilitate unidirectional interaction. Using these procedures consecutively yields an improved design method that provides interaction between spatial and structural design. A computer program in Prolog-2 has been developed for demonstration purposes. The method developed here can be applied flexibly because it is limited to only two procedures and there is the added advantage that the procedures can easily be extended or redefined.},
            note={MSc Thesis (in Dutch)},
            key={mscherm},
			link={https://research.tue.nl/en/studentTheses/konstruktief-ontwerpen-met-behulp-van-computerprogrammatuur},
        }
		@mastersthesis{mscjeffrey,
            author={Kuling, Jeffrey},
            title={Methodisch Genereren van een Constructief Ontwerp},
            school={Eindhoven University of Technology},
            year={2009},
            abstract={To improve the building design proces, a computer program has been envisioned that informs the architect whether a design is structurally sound. Requirements for the computer program have been investigated, and interviews with structural engineers  have been held to better understand their reasoning. As part of the program, the generation of structural systems, three methods have been suggested, respectively based on rastering, zoning, and grid locations. The rastering based method has been implemented, which works with: a set of pruned surfaces of the architectural walls; then based on this raster a generation of structural elements with a user selected direction; and finally with checks on the coverage of the archictural walls, and too small or large span lenghts. Finally, UML process diagrams have been developed for subsequent steps to be implemented.},
            note={MSc Thesis (in Dutch)},
            key={mscjeffrey},
			link={https://research.tue.nl/nl/studentTheses/methodisch-genereren-van-een-constructief-ontwerp},
        }
		@mastersthesis{mscbas,
            author={Van Limpt, Bas},
            title={Optimaliseren van het Constructief Ontwerpproces aan de Hand van Data en Procesmodellen},
            school={Eindhoven University of Technology},
            year={2011},
            abstract={Insights into the structural design process are needed to know where computer applications flourish. Therefore, in this project first an initial structural design was developed, based on a spatial design, following the steps learned in student design studios. Then, deliberately afterwards, the related process was described by process and data models, enforcing explicit reflection on the design process. Secondly, the data and process models were studied and improved. This involved for the process model the distinguishment of floor, stability, and vertical structural systems, and their relationships. The data model was more attuned to the requirements of the process model. Using these improved models, a new structural design was developed, and the initial and new designs were compared. This proved to be difficult, as both designs were carried out by the same student. Nevertheless, the generation of data and process models showed to gain insights and reflection on the design process.},
            note={MSc Thesis (in Dutch)},
            key={mscbas},
			link={https://research.tue.nl/nl/studentTheses/optimaliseren-van-het-constructief-ontwerpproces-aan-de-hand-van-},
        }
		@mastersthesis{msccarola,
            author={Smulders, Carola},
            title={StabilizeStruct: Automated Stabilization of Kinematically Undetermined Structures},
            school={Eindhoven University of Technology},
            year={2011},
            abstract={A spatial–structural design process can be investigated via a so-called research engine, in which a spatial design is transformed into a structural design and vice versa. During the transformation from a spatial into a structural design, it is necessary to obtain a stable structural model, so that a structural analysis can be carried out. This thesis presents four methods to automate the (normally carried out intuitively) stabilisation process, using data related to a structural design’s geometry and its instability modes. The methods all use the null space and associated null vectors of the structural stiffness matrix. Then each null vector is resolved by either (a) rod addition, (b) plane addition, (c) hinge fixation by single rod substitution, or (d) hinge fixation by coupled rod substitution. The methods have been implemented in C++ and several test cases have been carried out. The test cases explain why (a) rod addition provides the most realistic solutions, (b) if several methods are used subsequently for one problem, superfluous elements are inevitable, (c) there is a serious influence on the performance for various systems of key point numbering, (d) the efficiency of the methods is not optimal and may be improved by some suggested strategies.},
            note={MSc Thesis},
            key={msccarola},
			link={https://research.tue.nl/nl/publications/an-automated-stabilisation-method-for-spatial-to-structural-desig},
        }
		@mastersthesis{mscsjonnie,
            author={Boonstra, Sjonnie},
            title={Multi-Disciplinary Building Optimisation},
            school={Eindhoven University of Technology},
            year={2016},
            abstract={This thesis presents two methods and three tools that have been developed for use in multi-disciplinary building optimisation. The first method aims to increase the variation in building designs in an optimisation task by considering a super structure free and a super structured design space at the same time during one optimisation process. Two different building representations were defined, each suitable for one of the two considered design spaces. A tool has been developed to convert each building representation into the other and vice versa, this tool is envisioned to enable both design space types to be used during one optimisation task. The second method aims to automatically asses building designs on their performance with respect to building physics, i.e. required energy for climate control in a building. This automated process uses a simulation program to determine performances of spaces in the building model. A simulation tool was developed to simulate the heat balance of a building and the heating and cooling of spaces. The simulated energy required for heating and cooling of spaces is used to assess the performance of spaces with respect to the building. A 3D-conformation tool that is computationally fast was developed to make the representation of a building design compatible with the building physics simulation tool.},
            note={MSc Thesis},
            key={mscsjonnie},
			link={https://research.tue.nl/nl/studentTheses/multi-disciplinary-building-optimisation},
        }
		@mastersthesis{mscniels,
            author={Ten Heggeler, Niels},
            title={Load-Based Structural Topology Generation and Simultaneous Topology Optimization of Multiple Element Types},
            school={Eindhoven University of Technology},
            year={2016},
            abstract={For the development of a structural topology, structural grammars predefine locations of structural mass based on the building spatial design, whereas topology optimisation distributes structural mass freely and based on the loads. This thesis presents a new method that involves first an iterative structural grammar that uses finite element simulations to optimise an initial structural topology for minimal structural mass. Hereafter topology optimisation is applied to modify the structural topology elements for minimal compliance. Due to the several groups of structural topology elements involved, a separate volume fraction is maintained for each group. Using an academic case study, the method is compared to standard structural grammars and topology optimisation, defining Pareto fronts for the objectives structural volume and strain energy.},
            note={MSc Thesis},
            key={mscniels},
			link={https://research.tue.nl/en/studentTheses/load-based-structural-topology-generation-and-simultaneous-topolo},
        }
		@mastersthesis{mscdennis,
            author={Claessens, Dennis},
            title={Influence of Spatial Zoning on Structural Topology Performance},
            school={Eindhoven University of Technology},
            year={2018},
            abstract={Spatial zoning is the detection of zones in a building spatial design and the process of combining them into zoned designs. This thesis presents a three-dimensional spatial zoning procedure that is focussed on the creation of zoned designs that can be applied in a top-down approach for structural design. This method has been implemented in a toolbox for multidisciplinary building spatial design optimization along with two grammars for the creation of structural models and a stabilization procedure. Several case studies were carried out in which zoned designs were applied in two methods for structural design: (1) the creation of structural models and (2) the stabilization of a structural model. In these methods, the perimeters of either zones (zoned solutions) or spaces (unzoned solution) indicate the allowed locations for structural components or stabilizing structural adjustments. Pareto fronts were used to determine the efficiency of solutions in terms of strain energy and structural volume. This showed that application of spatial zoning to structural design generally has a positive effect on the performance of resultant structural topologies. It was also concluded that the appropriate allowance for space-intersecting zoned designs can have a positive influence on the efficiency of structural models, which was more often true for the creation of structural models than for stabilization.},
            note={MSc Thesis},
            key={mscdennis},
			link={https://research.tue.nl/en/studentTheses/influence-of-spatial-zoning-on-structural-topology-performance},
        }
		@mastersthesis{mscthijs,
            author={De Goede, Thijs},
            title={Co-Evolutionary Building Design Simulation for Structural Optimization with Facade Openings},
            school={Eindhoven University of Technology},
            year={2019},
            abstract={This thesis presents two alternative procedures for structural optimization via simulation of a co-evolutionary design process of a conceptual building spatial design. This simulation method applies structural optimization using automated building spatial design modifications that delete the worst-performing spaces and scale and subdivide the best-performing spaces. Structural performance of a building spatial design is expressed by its total sum of strain energy. Both procedures generate building spatial design representations with facade openings: one procedure reassigns a pattern of facade openings every simulation cycle, while the other procedure initializes facade openings only once and applies inheritance of these facade openings during the simulation. A parameter study is performed to study the effects of both procedures on the simulation of a co-evolutionary design process. The results of this parameter study show that the type of facade opening pattern influences the minimization of total strain energy during a building spatial design optimization. Namely, deterministic vertical patterns with a low facade opening ratio lead to larger reduction of the number of stories and therefore minimizes the total strain energy compared to those with higher ratios. Moreover, reassignment of facade opening patterns allows facade opening ratios to be constrained by a user-defined value during the simulation, whereas the inheritance of facade openings decreases openness of facades. Furthermore, the inheritance of facade openings generates substantially more unrealistic building spatial designs with floating spaces. Therefore, the reassignment of facade opening patterns is recommended for further research into development and optimization of conceptual building spatial designs.},
            note={MSc Thesis},
            key={mscthijs},
			link={https://research.tue.nl/en/studentTheses/co-evolutionary-building-design-simulation-for-structural-optimiz},
        }
		@mastersthesis{mscthomas,
            author={Snel, Thomas},
            title={Heuristic Modification Procedures for Building Spatial Design Optimization},
            school={Eindhoven University of Technology},
            year={2019},
            abstract={This research presents procedures developed for the heuristic optimization of early stage building spatial designs using simulations of co-evolutionary design processes. The research focuses on single disciplinary optimization and it shows that the procedure is capable of optimizing a building spatial design for either structural or building physics performance. Structural performance is defined as the total amount of strain energy, and building physics performance is defined as the thermal energy loss due to heating and cooling of spaces. The constraints for optimization are equal volume, equal space count, no overlap between spaces, and no floating spaces. The procedure is divided into three sub procedures: performance evaluation, space ranking, and building modification. For all stages multiple parameters are developed and elaborated. For the performance evaluation procedure it is shown that structural evaluation should rate spaces from best to worst as highest to lowest strain energy. Building physics evaluation should rate spaces from best to worst as lowest to highest thermal energy loss. Furthermore it can be stated that combining a geometrical clustering approach with the evaluated performances is capable of improving a building spatial design for both disciplines. The space ranking in this study is straightforward since only one discipline is considered at a time. For the building modification sub procedure the most effective parameters are those that move a building spatial design towards the most optimal shape for the given discipline. For structural optimization this means a one storey high, square floor plan. Building physics optimization finds the best solutions when the modifications move the building spatial design towards a cuboid design. Unfortunately, a part of the found solutions result in undesirable building spatial designs. These designs contain spaces that have unrealistic ratios between their height, width and depth.},
            note={MSc Thesis},
            key={msctomas},
			link={https://research.tue.nl/en/studentTheses/heuristic-modification-procedures-for-building-spatial-design-opt},
        }
		@mastersthesis{mscdiane,
            author={Schoenmaker, Diane},
            title={The Influence of Topology Optimisation Design Space—from Shell to Volume—on the Building Structural Design},
            school={Eindhoven University of Technology},
            year={2020},
            abstract={A part of design (decision) support systems comprises the automatic generation of a structural system for a building spatial design. This generation can be carried out by Topology Optimisation (TO), for which different geometrical design spaces can be selected. Here, three grammars to generate various TO (geometrical) design spaces are studied: (a) the Flat Shell Grammar (FSG), which initiates flat shells for each space surface; (b) a Partial Volume Grammar (PVG), which generates volumes for each surface; and (c) the Volume Grammar (VG) that sees the total volume of the building spatial design as the geometrical design space. By two case studies, it can be concluded that the more freedom a geometrical design space provides, the better the structural performance is. Also, structural systems suggested using PVG, with a large thickness of the volumes, are difficult to interpret. For future research, VG or PVG grammars are advised, including a study for non-rectangular designs and openings.},
            note={MSc Thesis},
            key={mscdiane},
			link={https://research.tue.nl/en/studentTheses/the-influence-of-topology-optimisation-design-space-on-the-buildi},
        }
		@mastersthesis{msctessa,
            author={Ezendam, Tessa},
            title={Two Geometry Conformal Methods for the Use in a Multi-Disciplinary Non-Orthogonal Building Spatial Design Optimisation Framework},
            school={Eindhoven University of Technology},
            year={2021},
            abstract={Two geometry conformal methods are presented to generate a conformal model for the use in a design and optimisation framework, which transforms a quad-hexahedron non-orthogonal building spatial design (NOBSD) to multiple discipline-specific models. This conformal model has multiple use-cases regarding discipline-specific model definition, such as element connection and intersection problems within a finite element mesh, definition of properties and loads, and it allows for the grouping of sub-parts of a spaces into zones for spatial layouts that are more logical from a disciplines point of view. The first method, the quad-hexahedron method, generates a conformal model by splitting a quad-hexahedron NOBSD in quadhexahedron geometry entities. The second method, the tetrahedron method, generates a conformal model by splitting the quad-hexahedron NOBSD in tetrahedron geometry entities. Both methods are demonstrated, analysed and compared. As a result, the following conclusions can be made. Future work on the geometry conformal methods is needed, since both methods are not able the obtain a conformal model for all NOBSD. However, the quad-hexahedron method is already able to generate a conformal model for a certain scope of NOBSD and is observed to be suitable for the mentioned use-cases. In addition, the tetrahedron method might be able to make a conformal model for NOBSDs consisting of tetrahedrons. This is an application area for which the quad-hexahedron method would not be applicable to, without making a hybrid between the two. As a result, future research may result in two geometry conformal methods each applicable in their own field of strength.},
            note={MSc Thesis},
            key={msctessa},
			link={https://research.tue.nl/en/studentTheses/two-geometry-conformal-methods-for-the-use-in-a-multi-disciplinar},
        }
		@mastersthesis{mscsebastiaan,
            author={Van Hassel, Sebastiaan},
            title={Machine Learning and Genetic Algorithms for Conformal Geometries in Design Support Systems},
            school={Eindhoven University of Technology},
            year={2022},
            abstract={To optimise both building designs and their underlying design processes, design support systems exist. For domain specific analyses, these systems benefit from a conformal (CF) representation for the Building Spatial Design (BSD). In a conformal representation, for all entities: the vertices of an entity are, if intersecting an-other entity, only allowed to coincide with this other entity's vertices. This thesis presents research on whether Machine Learning (ML) and Genetic Algorithms (GA) can be used to obtain a conformal geometry for BSDs. For ML, a neural network is trained to learn the complex relation between BSDs and their conformal representations. GAs are first used to find all quad-hexahedrons in the search space, then to find sets of quad-hexahedrons that form the conformal design. A trained ML model does provide outcomes, but not very useful, even with encoding the configuration type of the design. Differently, the GA finds conformal designs for many instances, even for some non-orthogonal designs.},
            note={MSc Thesis},
            key={mscsebastiaan},
			link={https://research.tue.nl/en/studentTheses/machine-learning-and-genetic-algorithms-for-conformal-geometries-},
        }
		@mastersthesis{mscsanne,
            author={Van der Wal, Sanne},
            title={Tying Overlapping Meshes for Building Spatial Design Optimization},
            school={Eindhoven University of Technology},
            year={2022},
            abstract={In the built environment, design systems exist that optimize building designs, simulate design processes and find an alternative structural system for a building. The Building Spatial design Optimization (BSO) Toolbox is such a design system that uses a conformal model representation to achieve a proper meshing. However, the Building Spatial Design is limited to orthogonal and specific non-orthogonal designs. A new method is developed which ties overlapping finite element meshes to generate structural design solutions. This method is an alternative for the partitioning of the design into a conformal model representation which is currently implemented in the BSO Toolbox. The method consists of several steps, finding the overlapping surfaces in the design, assign master and slave nodes, remove overlapping finite elements, and finally creating a tie. In this thesis the method is explained in detail, a demonstration and analysis on the method is given with a conclusion that the tie method is a promising method that needs further research and refinement for better implementation and greater design possibilities. Further research should be done on the type of matrix used and how to apply matrix operations efficiently to reduce computational time when implementing models with more spaces and finer meshes. Further refinement on the creation of clouds and tying nodes on multiple surfaces is needed for more accurate results. And eventually the use of the tie method on any arbitrary non-orthogonal building spatial design can be examined further for greater design possibilities.},
            note={MSc Thesis},
            key={mscsanne},
			link={https://research.tue.nl/en/studentTheses/tying-overlapping-meshes-for-building-spatial-design-optimization},
        }
		@mastersthesis{mscjanneke,
            author={Heuvelman, Janneke},
            title={Comparing Human, Human-AI, and AI-Automated Structural Design Processes and Products for Zoning and Stabilization},
            school={Eindhoven University of Technology},
            year={2024},
            abstract={AI agents are increasingly used in building design and engineering. Therefore, this study aims to investigate the impact of AI agents on the human structural design process. This is done by comparing human, human-AI, and AI-automated design processes and products, each approach characterized by a different level of AI involvement. Two AI agents are incorporated: zoning and stabilization. Zoning is the grouping of spaces to search for geometrically relevant shapes in a building, whereas stabilization is a process for preventing kinematic mechanisms in a building. To enable interaction between a human and the AI agent, Graphical User Interfaces were developed, providing a platform for assignments to be executed during this research’s core experiment. Participants’ processes were captured through a linkography analysis and a post-experimental questionnaire. Results from the experiment demonstrated that regarding task-specific products and total time spent, the AI agents used in this study outperformed participants in both the human and human-AI assignments. Although efficient, the AI agents primarily considered strain energy (stiffness) and lacked the ability to combine a multitude of variables. Integration of AI agents within a human design process showed potential, as the efficient AI agents streamlined human processes without diminishing creative freedom. Notably, collaboration with AI agents enhanced human products and processes only when participants defined a problem-solving strategy prior to accepting AI suggestions. Whereas participants who fully relied on AI suggestions from the start performed more poorly than humans without AI support.},
            note={MSc Thesis},
            key={mscjanneke},
			link={https://research.tue.nl/en/studentTheses/comparing-human-human-ai-and-ai-automated-structural-design-proce},
        }
		@mastersthesis{mscjildert,
            author={Turkstra, Jildert},
            title={AI Integration in Design Processes: A Study of Human, Human-AI, and AI-Automated Approaches in Co-Evolutionary Spatial-Structural Cycles},
            school={Eindhoven University of Technology},
            year={2024},
            abstract={The increasing complexity and sustainability challenges in the built environment necessitate more efficient design processes. Advances in Artificial Intelligence (AI) offer promising tools to enhance various aspects of building design. Despite significant progress in AI integration, there remains a limited understanding of how different levels of AI involvement affect the design process and its outcomes. Previous studies have highlighted AI’s potential to optimize design parameters but also pointed out its limitations in handling the iterative aspects of the design process. To address these gaps, a design studio experiment was conducted to compare the product and process outcomes of human-only, human-AI collaborative, and AI-only design approaches. The experiment involved participants completing the same design assignment using one of the three approaches. The results demonstrate that AI involvement generally enhances the optimization of structural parameters, particularly in reducing strain energy, although it can sometimes lead to increased structural volume. AI also facilitates the exploration of design possibilities, introducing solutions that human designers might not have considered. The study concludes that effective AI integration can lead to more efficient design solutions, providing valuable insights into the role and impact of AI in the design process.},
            note={MSc Thesis},
            key={mscjildert},
			link={https://research.tue.nl/en/studentTheses/ai-integration-in-design-processes-a-study-of-human-human-ai-and-},
        }
        @inproceedings{hofmeyer2005con,
            title={Improving Design using Autonomous Spatial and Structural Generators},
            author={Hofmeyer, Herm and Rutten, Harry and Fijneman, Henk},
            year={2005},
            abstract={During a building design process, a structural designer transforms a spatial design into a structural design and this structural system can be improved by optimisation methods or expert views of other structural designers. The improved structural system allows the architect a new spatial design, which can be transformed or altered again by the architect. This design cycle can be repeated several times and is defined as interaction of spatial and structural design. Case studies are used to demonstrate that this interaction occurs in practice and is needed to improve building quality. This paper presents a program with more or less autonomous spatial and structural generators. Each generator will facilitate one direction in the interaction process. Then using both consecutively leads to a design method that provides interaction between spatial and structural design. For the spatial generator, named “room positioning with structural constraints” a space allocation technique is used including constraints that handle structural boundary conditions. A zone generator based on pattern recognition and shape grammars handle the structural design. A Prolog-2 program was developed to demonstrate the application of the two proposed generators. “Zone generation” is performed per building storey and thus represents a horizontal two-dimensional procedure. Similarly “room positioning with structural constraints” is a planar vertical operation. In future these procedures can be made three-dimensional.},
            note={eCAADe, Lisbon, Portugal},
            link={https://research.tue.nl/en/publications/improving-design-using-autonomous-spatial-and-structural-generato}
        }
		
		 @inproceedings{hofmeyer2006con,
            title={Full 3D Structural Zoning of Space using a Geometrically Related Reducer and Matrix Coupling},
            author={Hofmeyer, Herm and Kerstens, Jan},
            year={2006},
            abstract={Structural zoning is the recognition of forms in spatial designs. It can be used by a structural designer to develop a structural system. This paper will start with the presentation of a proof that neither user action nor a two-dimensional approach -two existing approaches of zoning- are able to recognize all possibilities for the application of a structural design to a spatial design. Only full threedimensional structural zoning is considered to be an appropriate instrument to give useful solutions. Two new concepts will be presented to overcome problems for three-dimensional zoning: (1) Geometrically Related Reducers and (2) Matrix Coupling. These concepts are first defined in a general form and thereafter the definitions are condensed into a practically applicable format. Both concepts are demonstrated when finding rectangular zones in spatial designs up to 44 separate spatial entities. They are programmed procedurally using the C++ computer language and are used for a comparison between structural designers and computer performance.},
            note={CAADRIA, Kumamoto, Japan},
            link={https://research.tue.nl/en/publications/full-3d-structural-zoning-of-space-using-a-geometrically-related-}
        }
		
		@inproceedings{hofmeyer2007con,
            title={Positioning FEM in the Transformation of Spatial Design to Structural Design},
            author={Hofmeyer, Herm and Bakker, Monique},
            year={2007},
            abstract={In the field of architecture, structural topology is the set of locations, types (i.e. beams, columns), and arrangements of structural elements. To help the architect in understanding the structural topology for his spatial design, research exists that studies the process of the transformation of a spatial design into a structural design. If the Finite Element Method (FEM) is applied in this research, two problems can occur: (1) how to transform a topology in a mechanical system and FEM-input and (2) how can FEM support qualitative design decisions. In this paper, it is tried to define these two problems more clearly by developing data(EXPRESS)- and process(IDEF0)-models for three transformations: From structural topology to mechanical system, from mechanical system to finite element model, and from finite element model to design recommendations. A six-level apartment building is used as a case study to test and supplement the data- and process-models for all three transformations. It can be concluded that the data- and process models are useful at their abstract level, but that many problems at lower abstraction levels remain to be solved.},
            note={CIB-W78, Maribor, Slovenia},
            link={https://research.tue.nl/en/publications/positioning-fem-in-the-tranformation-of-spatial-design-to-structu}
        }
		
		@inproceedings{hofmeyer2008con,
            title={A Bird's-Eye View of Cyclic Spatial-Structural Transformations, Grammar Based Design, and Structural Optimization},
            author={Hofmeyer, Herm and Kerstens, Jan},
            year={2008},
            abstract={Recently, in the research field of combined architecture and structural design, the idea of a so-called research engine has been developed. During its development, initially the intention was to develop a design-support tool, however, it now becomes clear that it may serve as a general framework for several applications. In this paper the new possibilities for the applications will be presented. As a result, a bird’s-eye view is developed on a set of applications that are often presented separately and without a larger framework in literature. In conclusion, several applications used for CAAD and CASD (Computer Aided Structural Design) can be seen as derivatives of a research engine. The other way round, the research engine can be modified and new applications may result.},
            note={eCAADe, Antwerp, Belgium},
            link={https://research.tue.nl/en/publications/a-birds-eye-view-of-cyclic-spatial-structural-transformations-gra}
        }
		
		@inproceedings{hofmeyer2009con,
            title={Redefinition of Geometrical Components to Specify Kinematically Undetermined Behaviour},
            author={Hofmeyer, Herm and Gelbal, Firat},
            year={2009},
            abstract={A method for the redefinition of geometrical design components, to be used for specifying kinematically undetermined behaviour, is presented. It starts with checking all line-line combinations for intersection or for a line-line combination being collinear. If an intersection has been found, it is used to generate additional lines such that both old lines are split up at their intersection, resulting in new lines. For lines being collinear a similar approach is followed. Hereafter, all line-area combinations are checked. If certain conditions are met, new intersection points and lines are generated in the area to provide new areas that split up the old area correctly. The procedures (line-line and line-area) are repeated until convergence. Finally, pattern recognition is used to find all areas from the intersection points within an original area. A C++ program and a number of examples verify the method and test its efficiency.},
            note={CIB-W78, Istanbul, Turkey},
            link={https://research.tue.nl/en/publications/redefinition-of-geometrical-components-to-specify-kinematically-u}
        }
		
		@inproceedings{hofmeyer2009con2,
            title={Interaction between Spatial and Structural Building Design: A Finite Element Based Program for the Analysis of Kinematically Indeterminable Structural Topologies},
            author={Hofmeyer, Herm and Russell, Peter},
            year={2009},
            abstract={To understand the spatial and structural building design process and to help designers involved, the idea of a research engine has been developed: In this engine cyclic transformations take place between spatial and structural building designs. With this engine, a design process can be studied closely and subjected to improvement, and designers can be supported. The transformation from spatial to structural design consists of four sub transformations: (1) from spatial design to structural topology, (2) from structural topology to mechanical model, (3) from mechanical model to finite element model, and (4) from finite element model to design recommendations. Because in step (1) architectural elements are transformed into structural elements only, the resulting structural topologies are not a-priori kinematically determined. Therefore, in step (2), one of the problems to solve is the exact description of a kinematically indeterminable topology (at which nodes does spatial freedom exists and in which direction). In this paper a method for this description and its implementation will be presented, developed at RWTH Aachen University during a stay of the first author. The method starts with assigning specific finite elements, which define a relationship between element nodal forces and displacements, to each architectural element: Architectural columns are made by truss-elements, architectural beams with beam-elements, and architectural walls and floors are transformed into flat shell elements. For each element the local stiffness matrix and local coordinate system are calculated, whereafter global element stiffness matrices can be derived. These are merged into a system stiffness matrix, which is subsequently reduced for boundary conditions and reduced elements. Now, the null space of the stiffness matrix can be calculated, using the technique of singular value decomposition, which yields, after some further processing, exactly defined modes of spatial freedom related to the structural topology. The method was implemented for general 3D-cases in C++ and was checked for specific problems, which will also be presented in the paper. For further transformations in the research engine, the modes of spatial freedom should be suppressed, thus resulting in a kinematically determined structure that can be subjected to structural (and later architectural) optimization. In this paper also some suggestions will be made for methods (to be developed), which will make the design kinematically determined. The methods presented, partly implemented and partly in development, will be part of the research engine and as such will provide support to spatial and structural building designers and will provide insight and new developments in the design process of buildings itself.},
            note={CONVR, Sydney, Australia},
            link={https://research.tue.nl/en/publications/interaction-between-spatial-and-structural-building-design-a-fini}
        }
		
		@inproceedings{peeten2010con,
            title={Visualisation and Research Strategy for Computational Spatial and Structural Design Interaction},
            author={Peeten, Dennis and Hofmeyer, Herm},
            year={2010},
            abstract={A research engine is under development for studying the interaction of spatial and structural design processes. The design processes are being implemented as two separate configurable transformation steps; a conversion step and an optimisation step. A significant part of the spatial-to-structural conversion process together with a first version of a visualisation tool have been finalized. Because the interesting parts of spatial and structural designs are typically situated also on the inside of the design, the main goal of the visualisation tool is to make the innards visible from the outside. This has been realised by rendering translucent polygons with opaque outlines. However, care has to be taken in the order in which the translucent polygons are rendered. For an arbitrary set of convex polygons, finding a back to front order may not be as trivial as sorting a set of polygons on the distance to the viewpoint. Also, sets of polygons exist that do not have an explicit depth order. As a solution to this problem, a render engine has been developed that builds a binary space partition tree (BSP) to store the polygons. Another benefit of this BSP variant is that during the construction of the tree, difficult polygon arrangements are dealt with in an elegant matter. Further research involves the development of a complete version of the research engine. The performance of this first version will be compared to case studies. Based on these results, adjustments and additions to the research engine transformations will be made. The final version of the research engine will also be used to experiment on academic designs in order to develop insights in the fundamental relation between space and structure.},
            note={CIB-W78, Cairo, Egypt},
            link={https://research.tue.nl/en/publications/visualisation-and-research-strategy-for-computational-spatial-and}
        }
		
		@inproceedings{smulders2011con,
            title={An Automated Stabilization Method for Spatial-to-Structural Design Transformations},
            author={Smulders, Carola and Hofmeyer, Herm},
            year={2011},
            abstract={A spatial-structural design process can be investigated via a so-called research engine, in which a spatial design is transformed into a structural design and vice versa. During the transformation from a spatial into a structural design, it is necessary to end up with a stable structural model, so that a (static or dynamic) structural analysis can be carried out. This paper presents a method to automate the (normally intuitively carried out) stabilization process, using data on a structural design's geometry and its instability modes. The method uses the null space and associated null vectors of the structural stiffness matrix. Then each null vector is solved by connecting one of the vector's degree of freedom associated key points with a surrounding key point. Examples illustrate the method and demonstrate that predefined requirements have been met.},
            note={ASCE, Miami, USA},
            link={https://research.tue.nl/en/publications/an-automated-stabilization-method-for-spatial-to-structural-desig}
        }
		
		@inproceedings{hofmeyer2011con,
            title={Automatic Load Definition for Orthogonal Spatial and Structural Design},
            author={Hofmeyer, Herm},
            year={2011},
            abstract={Recently, the idea of a research engine has been developed, in which a spatial design is transformed into a structural design and vice versa by means of a cyclic procedure. Within this engine, a finite element model is applied that uses structural loads on the structural design that are derived from surface loads acting on the spatial design, such as wind loads, gravity loads, etc. This paper presents a method for the derivation of these structural loads from surface loads. The method is based on 1) finding the loaded surfaces among all surfaces of the spatial design; 2) selecting the structural elements that belong to the loaded surfaces; and 3) distributing the load among these structural elements. The new method functions correctly and will be combined with a recently developed procedure for stabilizing kinematically unstable structural systems to finish the research engine's spatial-structural transformation part.
1},
            link={https://research.tue.nl/en/publications/automatic-load-definition-for-orthogonal-spatial-and-structural-d}
        }
		
    `;

    let articles = [];

    function parseBibtex(bibtex) {
        const entries = bibtex.trim().split(/\n\s*@/).slice(1);
        const parsedArticles = entries.map(entry => {
            entry = '@' + entry.trim();  // Add @ back for consistent formatting
            const [, type, body] = entry.match(/@(\w+)\{([^]+)\}/) || [];
            if (!type || !body) {
                return null;
            }
            const fields = body.split(',\n').reduce((acc, field) => {
                const [key, value] = field.split('=').map(str => str.trim().replace(/[{}"]/g, ''));
                if (key && value) {
                    acc[key] = value;
                }
                return acc;
            }, {});
            fields.key = entry.match(/@(\w+)\{([^,]+),/)[2]; // Extract key
            return { type, ...fields };
        }).filter(article => article !== null);
        return parsedArticles;
    }

    function createPersonTile(name) {
        const lastName = name.split(',')[0].trim().split(' ').pop();  // Extract last name
        const col = document.createElement('div');
        col.className = 'col-md-3 col-sm-6';
        col.innerHTML = `
            <div class="tile" onclick="showToastAndFilterArticles('${name}')">
                <img src="images/person_${lastName}.jpg" alt="${name}" class="img-fluid">
                <h3>${name}</h3>
            </div>
        `;
        return col;
    }

    function createPhDThesisTile(thesis) {
        const col = document.createElement('div');
        col.className = 'col-md-4 col-sm-6';
        col.innerHTML = `
            <div class="tile" onclick="showThesisModal('${thesis.key}')">
                <img src="images/phdthesis_${thesis.key}.jpg" alt="${thesis.title}" class="img-fluid">
                <h3>${thesis.title}</h3>
                <p>${thesis.author} (${thesis.year})</p>
            </div>
        `;
        return col;
    }

    function createMScThesisTile(thesis) {
        const col = document.createElement('div');
        col.className = 'col-md-4 col-sm-6';
        col.innerHTML = `
            <div class="tile" onclick="showThesisModal('${thesis.key}')">
                <img src="images/mastersthesis_${thesis.key}.jpg" alt="${thesis.title}" class="img-fluid">
                <h3>${thesis.title}</h3>
                <p>${thesis.author} (${thesis.year})</p>
            </div>
        `;
        return col;
    }

    function createConferenceThesisTile(thesis) {
        const col = document.createElement('div');
        col.className = 'col-md-4 col-sm-6';
        col.innerHTML = `
            <div class="tile" onclick="showThesisModal('${thesis.key}')">
                <img src="images/inproceedings_${thesis.key}.jpg" alt="${thesis.title}" class="img-fluid">
                <h3>${thesis.title}</h3>
                <p>${thesis.author} (${thesis.year})</p>
            </div>
        `;
        return col;
    }

    function createArticleTile(article) {
        const col = document.createElement('div');
        col.className = 'col-md-4 col-sm-6';
        col.innerHTML = `
            <div class="tile" onclick="showArticleModal('${article.key}')">
                <img src="images/article_${article.key}.jpg" alt="${article.title}" class="img-fluid">
                <h3>${article.title}</h3>
                <p>${article.author} (${article.year})</p>
            </div>
        `;
        return col;
    }

    function populatePeople(articles) {
        const peopleSet = new Set();
        articles.forEach(article => {
            const authors = article.author.split(' and ');
            authors.forEach(author => peopleSet.add(author.trim()));
        });
        const peopleSection = document.getElementById('people').querySelector('.row');
        peopleSet.forEach(name => {
            const personTile = createPersonTile(name);
            peopleSection.appendChild(personTile);
        });
    }

    function populatePhDTheses(articles) {
        const thesesSet = new Set(articles.filter(article => article.type === 'phdthesis').map(article => ({ key: article.key, title: article.title, description: article.note, author: article.author, year: article.year || '' })));
        const thesesSection = document.getElementById('theses').querySelector('.row');
        thesesSection.innerHTML = ''; // Clear previous article
        thesesSet.forEach(thesis => {
            const thesisTile = createPhDThesisTile(thesis);
            thesesSection.appendChild(thesisTile);
        });
    }

    function populateMScTheses(articles) {
        const thesesSet = new Set(articles.filter(article => article.type === 'mastersthesis').map(article => ({ key: article.key, title: article.title, description: article.note, author: article.author, year: article.year || '' })));
        const thesesSection = document.getElementById('msctheses').querySelector('.row');
        thesesSection.innerHTML = ''; // Clear previous article
        thesesSet.forEach(thesis => {
            const thesisTile = createMScThesisTile(thesis);
            thesesSection.appendChild(thesisTile);
        });
    }
    

    function populateArticles(articles) {
        only_articles = articles.filter(article => article.type === 'article');
        const articleSection = document.getElementById('articles').querySelector('.row');
        articleSection.innerHTML = ''; // Clear previous articles
        only_articles.forEach(article => {
            const articleTile = createArticleTile(article);
            articleSection.appendChild(articleTile);
        });
    }

    function populateConferences(articles) {
        const conferenceSet = new Set(articles.filter(article => article.type === 'inproceedings').map(article => ({ key: article.key, title: article.title, description: article.note, author: article.author, year: article.year || '' })));
        const conferenceSection = document.getElementById('conferences').querySelector('.row');
        conferenceSection.innerHTML = ''; // Clear previous article
        conferenceSet.forEach(thesis => {
            const conferenceTile = createConferenceThesisTile(thesis);
            conferenceSection.appendChild(conferenceTile);
        });
    }

    function init() {
        articles = parseBibtex(bibtexData);
        populatePeople(articles);
        populatePhDTheses(articles);
        populateMScTheses(articles);
        populateArticles(articles);
        populateConferences(articles);
    }

    init();

    window.showToastAndFilterArticles = function(author) {
        const toastHTML = `
            <div class="toast">
                <div class="toast-header">
                    <strong class="mr-auto">Currently selected for: ${author}</strong>
                </div>
                <div class="toast-body">
                    View this author's work below or click 'Reset' to view all positions.<br/><br/>
                    <button class="btn btn-secondary mb-3" onclick="resetArticles();" data-dismiss="toast">Reset</button>
                </div>
            </div>
        `;
        const toastContainer = document.getElementById('toastContainer');
        toastContainer.innerHTML = toastHTML;
        $('.toast').toast({ autohide: false });
        $('.toast').toast('show');
        filterArticles(author);
    };

    window.filterArticles = function(author) {
        const filteredArticles = articles.filter(article => article.author.includes(author));
        populateArticles(filteredArticles);

        const filteredPhds = articles.filter(article => article.type === 'phdthesis' && article.author.includes(author));
        populatePhDTheses(filteredPhds);

        const filteredMSc = articles.filter(article => article.type === 'mastersthesis' && article.author.includes(author));
        populateMScTheses(filteredMSc);

        const filteredConferences = articles.filter(article => article.type === 'inproceedings' && article.author.includes(author));
        populateConferences(filteredConferences);

        document.getElementById('resetButton').style.display = 'block';
    };

    window.resetArticles = function() {
        populateArticles(articles);
        populateMScTheses(articles);
        populatePhDTheses(articles);
        populateConferences(articles);
        document.getElementById('resetButton').style.display = 'none';
    };

    window.showThesisModal = function(thesisKey) {
        const thesis = articles.find(a => a.key === thesisKey);
        const authors = thesis.author.split(' and ').map(author => `<a href="javascript:showToastAndFilterArticles('${author.trim()}')">${author.trim()}</a>`).join(', ');

        $('#thesisModalLabel').text(thesis.title);
        $('#thesisModalDesc').html(`
            <p><strong>Author:</strong> ${authors}</p>
            <p><strong>Year:</strong> ${thesis.year}</p>
            <p><strong>Abstract:</strong> ${thesis.abstract || 'No abstract available.'}</p>
            <p><strong>Note:</strong> ${thesis.note || 'No additional notes.'}</p>
            <p><strong>Link:</strong> <a href="${thesis.link}" target="_blank">${thesis.link}</a></p>
        `);
        $('#thesisModal').modal('show');
    };

    window.showArticleModal = function(articleKey) {
        const article = articles.find(a => a.key === articleKey);
        const authors = article.author.split(' and ').map(author => `<a href="javascript:showToastAndFilterArticles('${author.trim()}')">${author.trim()}</a>`).join(', ');

        $('#articleModalLabel').text(article.title);
        $('#articleModalDesc').html(`
            <p><strong>Authors:</strong> ${authors}</p>
            <p><strong>Journal:</strong> ${article.journal}</p>
            <p><strong>Year:</strong> ${article.year}</p>
            <p><strong>Volume:</strong> ${article.volume}</p>
            <p><strong>Pages:</strong> ${article.pages}</p>
            <p><strong>Abstract:</strong> ${article.abstract || 'No abstract available.'}</p>
            <p><strong>Note:</strong> ${article.note || 'No additional notes.'}</p>
            <p><strong>Link:</strong> <a href="${article.link}" target="_blank">${article.link}</a></p>
        `);
        $('#articleModal').modal('show');
    };
});